tasks:
  - name: kubeconfig
    actions:
      - description: Setup the cluster connection (kubeconfig)
        cmd: |
          set -e
          mkdir -p ~/.kube
          aws s3 cp s3://uds-$ENVIRONMENT-cluster-rke2/rke2.yaml ~/.kube/config
          set +e

      - description: Cleanup single self-hosted runner
        cmd: |
          sudo rm -rf /tmp/zarf-*.log
          sudo rm -rf /tmp/uds-*.log
          sudo rm -rf uds-*.tar.zst # Remove outdated bundles

      - description: Wait for cluster connection
        wait:
          cluster:
            kind: Service
            name: kubernetes
