# This is overwritten at deploy time by the config file from secretsmanager
options:
  architecture: amd64

variables:
  init:
    # Workaround for SELinux EBS issue - https://github.com/bottlerocket-os/bottlerocket/issues/2417
    registry_hpa_enable: false
    registry_pvc_size: 50Gi
  aws-lb-controller:
    cluster_name: $ENVIRONMENT
    lb_role_arn: $LB_ROLE_ARN
  uds-core:
    tenant_eip_allocations: $TENANT_EIP_ALLOCATIONS
    passthrough_eip_allocations: $PASSTHROUGH_EIP_ALLOCATIONS
