bundle:
  deploy:
    architecture: amd64
    zarf-packages:
      init:
        set:
          # Workaround for SELinux EBS issue - https://github.com/bottlerocket-os/bottlerocket/issues/2417
          registry_hpa_enable: false
      uds-core:
        set:
          domain: burning.boats
