name: Terraform Scanning
description: Scan using common checks in Terraform

inputs:
  target:
    description: Target directory under terraform
    required: true

runs:
  using: composite
  steps:
    - uses: terraform-linters/setup-tflint@v4
      name: Setup TFLint
      with:
        tflint_version: latest

    - name: Init TFLint
      run: tflint --init
      shell: bash
      env:
        # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
        GITHUB_TOKEN: ${{ github.token }}

    - name: Run TFLint
      run: tflint -f compact
      working-directory: './terraform/${{ inputs.target }}/'
      shell: bash
