# This is overwritten at deploy time by the config file from secretsmanager
shared:
  bucket_suffix: "-$ENVIRONMENT"

variables:
  swf-deps-aws:
    postgres_db_password: $POSTGRES_DB_PASSWORD
    redis_password: $REDIS_PASSWORD
  gitlab:
    gitlab_redis_endpoint: $REDIS_ENDPOINT
    postgres_db_endpoint: $POSTGRES_DB_ENDPOINT
    registry_role_arn: "$REGISTRY_ROLE_ARN"
    sidekiq_role_arn: "$SIDEKIQ_ROLE_ARN"
    webservice_role_arn: "$WEBSERVICE_ROLE_ARN"
    toolbox_role_arn: "$TOOLBOX_ROLE_ARN"
