name: Test Burn the Boats
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

permissions:
  contents: write
  id-token: write
  pull-requests: write

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      vpc_changes: ${{ steps.changes.outputs.vpc }}
      irsa_changes: ${{ steps.changes.outputs.irsa }}
      cluster_changes: ${{ steps.changes.outputs.cluster }}
      swf_changes: ${{ steps.changes.outputs.swf }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Check paths
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            vpc:
              - 'terraform/vpc/**'
              - 'env/burn-the-boats/vpc.tfvars'
              - '.github/actions/terraform-test/**'
              - '.github/workflows/**'
            irsa:
              - 'terraform/irsa/**'
              - 'env/burn-the-boats/irsa.tfvars'
              - '.github/actions/terraform-deploy/**'
              - '.github/workflows/**'
            cluster:
              - 'terraform/cluster/**'
              - 'env/burn-the-boats/cluster.tfvars'
              - '.github/actions/terraform-test/**'
              - '.github/workflows/**'
            swf:
              - 'terraform/swf/**'
              - 'modules/irsa-s3/**'
              - 'modules/irsa-rdb/**'
              - 'modules/irsa-elasticache/**'
              - 'env/burn-the-boats/swf.tfvars'
              - '.github/actions/terraform-test/**'
              - '.github/workflows/**'

  vpc_checks:
    needs: check_changes
    if: needs.check_changes.outputs.vpc_changes == 'true'
    environment: burn-the-boats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/terraform-test
        with:
          environment: burn-the-boats
          target: vpc
        env:
          AWS_GOVCLOUD_ROLE_TO_ASSUME: ${{ secrets.AWS_GOVCLOUD_ROLE_TO_ASSUME }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          PERMISSIONS_BOUNDARY: ${{ vars.PERMISSIONS_BOUNDARY }}
          STATE_BUCKET: ${{ vars.STATE_BUCKET }}
          LOCK_TABLE: ${{ vars.LOCK_TABLE }}

  irsa_checks:
    needs: check_changes
    if: needs.check_changes.outputs.irsa_changes == 'true'
    environment: burn-the-boats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/terraform-test
        with:
          environment: burn-the-boats
          target: irsa
        env:
          AWS_GOVCLOUD_ROLE_TO_ASSUME: ${{ secrets.AWS_GOVCLOUD_ROLE_TO_ASSUME }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          PERMISSIONS_BOUNDARY: ${{ vars.PERMISSIONS_BOUNDARY }}
          STATE_BUCKET: ${{ vars.STATE_BUCKET }}
          LOCK_TABLE: ${{ vars.LOCK_TABLE }}

  cluster_checks:
    needs: 
      - check_changes
      - vpc_checks
      - irsa_checks
    if: ${{ always() && ( needs.vpc_checks.result == 'success' || needs.vpc_checks.result == 'skipped' ) && ( needs.irsa_checks.result == 'success' || needs.irsa_checks.result == 'skipped' ) && needs.check_changes.outputs.cluster_changes == 'true' }}
    environment: burn-the-boats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/terraform-test
        with:
          environment: burn-the-boats
          target: cluster
        env:
          AWS_GOVCLOUD_ROLE_TO_ASSUME: ${{ secrets.AWS_GOVCLOUD_ROLE_TO_ASSUME }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          PERMISSIONS_BOUNDARY: ${{ vars.PERMISSIONS_BOUNDARY }}
          STATE_BUCKET: ${{ vars.STATE_BUCKET }}
          LOCK_TABLE: ${{ vars.LOCK_TABLE }}

  swf_checks:
    needs:
      - check_changes
      - cluster_checks
    if: ${{ always() && ( needs.cluster_checks.result == 'success' || needs.cluster_checks.result == 'skipped' ) && needs.check_changes.outputs.swf_changes == 'true' }}
    environment: burn-the-boats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/terraform-test
        with:
          environment: burn-the-boats
          target: swf
        env:
          AWS_GOVCLOUD_ROLE_TO_ASSUME: ${{ secrets.AWS_GOVCLOUD_ROLE_TO_ASSUME }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          PERMISSIONS_BOUNDARY: ${{ vars.PERMISSIONS_BOUNDARY }}
          STATE_BUCKET: ${{ vars.STATE_BUCKET }}
          LOCK_TABLE: ${{ vars.LOCK_TABLE }}
