name: Test Burn the Boats
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - main

permissions:
  contents: write
  id-token: write
  pull-requests: write
  packages: read

jobs:
  check_changes:
    runs-on: ubuntu-latest
    outputs:
      vpc_changes: ${{ steps.changes.outputs.vpc }}
      irsa_changes: ${{ steps.changes.outputs.irsa }}
      cluster_changes: ${{ steps.changes.outputs.cluster }}
      swf_changes: ${{ steps.changes.outputs.swf }}
      base_bundle_changes: ${{ steps.changes.outputs.base_bundle }}
      swf_bundle_changes: ${{ steps.changes.outputs.swf_bundle }}
      lfai_bundle_changes: ${{ steps.changes.outputs.lfai_bundle }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Check paths
        uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            vpc:
              - 'terraform/vpc/**'
              - 'env/btb/vpc.tfvars'
              - '.github/actions/terraform-test/**'
              - '.github/workflows/**'
            irsa:
              - 'terraform/irsa/**'
              - 'env/btb/irsa.tfvars'
              - '.github/actions/terraform-deploy/**'
              - '.github/workflows/**'
            cluster:
              - 'terraform/cluster/**'
              - 'env/btb/cluster.tfvars'
              - '.github/actions/terraform-test/**'
              - '.github/workflows/**'
            swf:
              - 'terraform/swf/**'
              - 'modules/irsa-s3/**'
              - 'modules/irsa-rdb/**'
              - 'modules/irsa-elasticache/**'
              - 'env/btb/swf.tfvars'
              - '.github/actions/terraform-test/**'
              - '.github/workflows/**'
            base_bundle:
              - 'bundles/base/**'
              - 'tasks/**'
              - '.github/workflows/**'
              - 'terraform/cluster/uds-config.tf'
              - 'src/aws-lb-controller/**'
            swf_bundle:
              - 'bundles/swf/**'
              - 'tasks/**'
              - '.github/workflows/**'
              - 'terraform/swf/uds-config.tf'
              - 'src/swf-deps-aws/**'
            lfai_bundle:
              - 'bundles/lfai/**'
              - 'tasks/**'
              - '.github/workflows/**'
              - 'src/gpu-operator/**'

  vpc_checks:
    needs: check_changes
    if: needs.check_changes.outputs.vpc_changes == 'true'
    environment: btb
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/terraform-test
        with:
          environment: btb
          target: vpc
        env:
          AWS_GOVCLOUD_ROLE_TO_ASSUME: ${{ secrets.AWS_GOVCLOUD_ROLE_TO_ASSUME }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          PERMISSIONS_BOUNDARY: ${{ vars.PERMISSIONS_BOUNDARY }}
          STATE_BUCKET: ${{ vars.STATE_BUCKET }}
          LOCK_TABLE: ${{ vars.LOCK_TABLE }}

  irsa_checks:
    needs: check_changes
    if: needs.check_changes.outputs.irsa_changes == 'true'
    environment: btb
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/terraform-test
        with:
          environment: btb
          target: irsa
        env:
          AWS_GOVCLOUD_ROLE_TO_ASSUME: ${{ secrets.AWS_GOVCLOUD_ROLE_TO_ASSUME }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          PERMISSIONS_BOUNDARY: ${{ vars.PERMISSIONS_BOUNDARY }}
          STATE_BUCKET: ${{ vars.STATE_BUCKET }}
          LOCK_TABLE: ${{ vars.LOCK_TABLE }}

  cluster_checks:
    needs: 
      - check_changes
      - vpc_checks
      - irsa_checks
    if: ${{ ( !cancelled() ) && ( needs.vpc_checks.result == 'success' || needs.vpc_checks.result == 'skipped' ) && ( needs.irsa_checks.result == 'success' || needs.irsa_checks.result == 'skipped' ) && needs.check_changes.outputs.cluster_changes == 'true' }}
    environment: btb
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/terraform-test
        with:
          environment: btb
          target: cluster
        env:
          AWS_GOVCLOUD_ROLE_TO_ASSUME: ${{ secrets.AWS_GOVCLOUD_ROLE_TO_ASSUME }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          PERMISSIONS_BOUNDARY: ${{ vars.PERMISSIONS_BOUNDARY }}
          STATE_BUCKET: ${{ vars.STATE_BUCKET }}
          LOCK_TABLE: ${{ vars.LOCK_TABLE }}
  swf_checks:
    needs:
      - check_changes
      - cluster_checks
    if: ${{ ( !cancelled() ) && ( needs.cluster_checks.result == 'success' || needs.cluster_checks.result == 'skipped' ) && needs.check_changes.outputs.swf_changes == 'true' }}
    environment: btb
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/terraform-test
        with:
          environment: btb
          target: swf
        env:
          AWS_GOVCLOUD_ROLE_TO_ASSUME: ${{ secrets.AWS_GOVCLOUD_ROLE_TO_ASSUME }}
          AWS_REGION: ${{ vars.AWS_REGION }}
          PERMISSIONS_BOUNDARY: ${{ vars.PERMISSIONS_BOUNDARY }}
          STATE_BUCKET: ${{ vars.STATE_BUCKET }}
          LOCK_TABLE: ${{ vars.LOCK_TABLE }}

  base_bundle_checks:
    needs:
      - check_changes
      - cluster_checks
      - swf_checks
    if: |
      ( !cancelled() ) &&
      ( needs.cluster_checks.result == 'success' || needs.cluster_checks.result == 'skipped' ) &&
      ( needs.swf_checks.result == 'success' || needs.swf_checks.result == 'skipped' ) &&
      needs.check_changes.outputs.base_bundle_changes == 'true'
    environment: btb
    runs-on: [self-hosted, staging]
    steps:
      - uses: actions/checkout@v4

      - name: Setup runner
        shell: bash
        run: uds run setup
        env:
          ENVIRONMENT: btb

      - name: Environment setup
        uses: ./.github/actions/setup
  
      - name: GHCR Login
        run: zarf tools registry login -u "dummy" -p "${{ secrets.GITHUB_TOKEN }}" ghcr.io

      - name: Test creation of base bundle
        shell: bash
        run: uds run create-base

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs
        with:
          suffix: -base-bundle-checks

  swf_bundle_checks:
    needs:
      - check_changes
      - base_bundle_checks
    if: |
      ( !cancelled() ) &&
      ( needs.base_bundle_checks.result == 'success' || needs.base_bundle_checks.result == 'skipped' ) &&
      needs.check_changes.outputs.swf_bundle_changes == 'true'
    environment: btb
    runs-on: [self-hosted, staging]
    steps:
      - uses: actions/checkout@v4

      - name: Setup runner
        shell: bash
        run: uds run setup
        env:
          ENVIRONMENT: btb

      - name: GHCR Login
        run: zarf tools registry login -u "dummy" -p "${{ secrets.GITHUB_TOKEN }}" ghcr.io

      - name: Test creation of the swf bundle
        shell: bash
        run: uds run create-swf

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs
        with:
          suffix: -swf-bundle-checks

  lfai_bundle_checks:
    needs:
      - check_changes
      - swf_bundle_checks
    if: |
      ( !cancelled() ) &&
      ( needs.swf_bundle_checks.result == 'success' || needs.swf_bundle_checks.result == 'skipped' ) &&
      needs.check_changes.outputs.lfai_bundle_changes == 'true'
    environment: btb
    runs-on: [self-hosted, staging]
    steps:
      - uses: actions/checkout@v4

      - name: Setup runner
        shell: bash
        run: uds run setup
        env:
          ENVIRONMENT: btb

      - name: GHCR Login
        run: zarf tools registry login -u "dummy" -p "${{ secrets.GITHUB_TOKEN }}" ghcr.io

      - name: Test creation of the lfai bundle
        shell: bash
        run: uds run create-lfai

      - name: Save logs
        if: always()
        uses: ./.github/actions/save-logs
        with:
          suffix: -lfai-bundle-checks
